# Generated by Django 2.0 on 2018-07-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('capital', models.CharField(max_length=25)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=25)),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=25)),
            ],
        ),
    ]
