# Generated by Django 2.0 on 2018-07-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ('state',)},
        ),
        migrations.AlterField(
            model_name='state',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=25),
        ),
        migrations.AlterField(
            model_name='state',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=25),
        ),
    ]
