# Generated by Django 2.0 on 2018-08-29 06:52

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('state', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cord',
            new_name='Coord',
        ),
        migrations.RenameField(
            model_name='coord',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='coord',
            old_name='longitude',
            new_name='lon',
        ),
        migrations.RenameField(
            model_name='lga',
            old_name='cord',
            new_name='coord',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='cord',
            new_name='coord',
        ),
    ]
