# Generated by Django 2.0 on 2018-07-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_auto_20180719_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='state',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
